### ISSUE TITLE
Availability of codes and models

### ISSUE THREAD

**Issue by lkpengcs** [BAAI-DCAI/M3D#1]
Hi, I would like to know when the codes and models will be available. Thank you!

**Comment by baifanxxx** [comment]
Hi, you can view the code and model now. We will soon improve the README and details. Stay tuned.

**Comment by baifanxxx** [comment]
Hi, 

I appreciate your interest in our work. You can view the code and model now. We will improve the README and details soon. Please stay tuned.

Best regards,
BAI Fan
