### ISSUE TITLE
How to Visualize Detection Results from Coordinates in Quickstart?

### ISSUE THREAD

**Issue by VinyehShaw** [BAAI-DCAI/M3D#11]
Hello,

I encountered an issue while trying to follow the Quickstart guide provided in the README. When I use the question `question = "What is liver in this image? Please output the box."`, I only receive coordinates and am unable to visualize the detection results.

The specific returned result is: `generated_texts Coordinates are [0.594, 0.34, 0.414, 0.938, 0.914, 0.895]`.

I would like to know how to use these coordinates to draw the detection box on the image for better visualization. Could you provide guidance or an example on how to achieve this?

Additionally, could you provide the ground truth for the example data used in Quickstart? This would greatly help in validating and comparing the results.

Thank you!

**Comment by baifanxxx** [comment]
Hi,

You can find the visualization method here (https://github.com/BAAI-DCAI/M3D/blob/05bb41a29a9dcb5afe8dcafc2c0222b45e271c2a/Bench/eval/eval_pos.py#L148).

Best regards,
BAI Fan
