### ISSUE TITLE
Lora Finetuning with self finetuned ViT and adapter

### ISSUE THREAD

**Issue by moritzlangenberg** [BAAI-DCAI/M3D#12]
Hello, 

How should I run the LoRA finetuning with an own pretrained ViT and pretrained adapter? Do I use `--pretrain_mllm` to give the full pretrained model checkpoint which I get from `pretrain.sh?`

Best,
Moritz

**Comment by baifanxxx** [comment]
Hi Moritz,

Of course, you can run the LoRA finetuning with your pretrained ViT and pretrained adapter. ‘--pretrain_mllm’ is selectable, which means that you can use the full pretrained model or pretrained multiple part modules.

Best,
BAI Fan
