### ISSUE TITLE
ImportError: cannot import name 'Phi3Config' from 'transformers'

### ISSUE THREAD

**Issue by sujaly** [BAAI-DCAI/M3D#13]
transformers==4.39.1 has no Phi3Config,
How do you run it?

**Comment by moritzlangenberg** [comment]
You need the development version of transformers as stated [here](https://huggingface.co/docs/transformers/main/en/model_doc/phi3). Do this by running `pip uninstall -y transformers && pip install git+https://github.com/huggingface/transformers`

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by sujaly** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
