### ISSUE TITLE
Problem about ITRdataset

### ISSUE THREAD

**Issue by WuSiying315** [BAAI-DCAI/M3D#16]
Hello,

Thanks for your excellent work. I am trying to reproduce the results of  Image-Text Retrieval, but I can't find the test file /M3D_Cap_npy/M3D_Cap_eh.json. Can you provide the test data? Thanks a lot！

**Comment by baifanxxx** [comment]
Hi,

I'm sorry for the late reply.
You can find test sets of different sizes here (https://huggingface.co/datasets/GoodBaiBai88/M3D-Cap/blob/main/M3D_Cap/M3D_Cap.json).
M3D_Cap_eh.json is removed and merged to M3D_Cap.json.
