### ISSUE TITLE
M3D-Cap downloading issue

### ISSUE THREAD

**Issue by ruida** [BAAI-DCAI/M3D#2]
Hi, 

I use git clone https://huggingface.co/datasets/GoodBaiBai88/M3D-Cap to get the M3D-Cap data.    The following message shows the downloaded files issue.    

Those zip files reflect internal errors.  
  

Cloning into 'M3D-Cap'...
remote: Enumerating objects: 6616, done.
remote: Counting objects: 100% (6616/6616), done.
remote: Compressing objects: 100% (6483/6483), done.
remote: Total 6616 (delta 121), reused 6616 (delta 121), pack-reused 0 (from 0)
Receiving objects: 100% (6616/6616), 991.60 KiB | 7.03 MiB/s, done.
Resolving deltas: 100% (121/121), done.
Updating files: 100% (6215/6215), done.
Filtering content: 100% (6188/6188), 204.65 GiB | 6.68 MiB/s, done.
Encountered 83 file(s) that may not have been copied correctly on Windows:
	M3D_Cap/ct_quizze/ct_quizze_03.zip
	M3D_Cap/ct_case/ct_case_06.zip
	M3D_Cap/ct_case/ct_case_03.zip
	M3D_Cap/ct_case/ct_case_02.zip
	M3D_Cap/ct_case/ct_case_01.zip
	M3D_Cap/ct_case/ct_case_05.zip
	M3D_Cap/ct_case/ct_case_00.zip
	M3D_Cap/ct_case/ct_case_04.zip
	M3D_Cap/ct_quizze/ct_quizze_01.zip
	M3D_Cap/ct_quizze/ct_quizze_00.zip
	M3D_Cap/ct_case/ct_case_10.zip
	M3D_Cap/ct_quizze/ct_quizze_02.zip
	M3D_Cap/ct_case/ct_case_15.zip
	M3D_Cap/ct_quizze/ct_quizze_27.zip
	M3D_Cap/ct_case/ct_case_13.zip
	M3D_Cap/ct_case/ct_case_07.zip
	M3D_Cap/ct_case/ct_case_11.zip
	M3D_Cap/ct_case/ct_case_16.zip
	M3D_Cap/ct_quizze/ct_quizze_04.zip
	M3D_Cap/ct_case/ct_case_12.zip
	M3D_Cap/ct_case/ct_case_17.zip
	M3D_Cap/ct_case/ct_case_19.zip
	M3D_Cap/ct_case/ct_case_18.zip
	M3D_Cap/ct_case/ct_case_20.zip
	M3D_Cap/ct_case/ct_case_24.zip
	M3D_Cap/ct_case/ct_case_21.zip
	M3D_Cap/ct_case/ct_case_14.zip
	M3D_Cap/ct_case/ct_case_58.zip
	M3D_Cap/ct_quizze/ct_quizze_12.zip
	M3D_Cap/ct_quizze/ct_quizze_26.zip
	M3D_Cap/ct_case/ct_case_23.zip
	M3D_Cap/ct_case/ct_case_09.zip
	M3D_Cap/ct_case/ct_case_08.zip
	M3D_Cap/ct_case/ct_case_22.zip
	M3D_Cap/ct_quizze/ct_quizze_10.zip
	M3D_Cap/ct_quizze/ct_quizze_11.zip
	M3D_Cap/ct_case/ct_case_28.zip
	M3D_Cap/ct_quizze/ct_quizze_13.zip
	M3D_Cap/ct_quizze/ct_quizze_19.zip
	M3D_Cap/ct_quizze/ct_quizze_08.zip
	M3D_Cap/ct_quizze/ct_quizze_05.zip
	M3D_Cap/ct_case/ct_case_61.zip
	M3D_Cap/ct_case/ct_case_27.zip
	M3D_Cap/ct_quizze/ct_quizze_17.zip
	M3D_Cap/ct_quizze/ct_quizze_15.zip
	M3D_Cap/ct_quizze/ct_quizze_09.zip
	M3D_Cap/ct_case/ct_case_30.zip
	M3D_Cap/ct_case/ct_case_26.zip
	M3D_Cap/ct_quizze/ct_quizze_14.zip
	M3D_Cap/ct_quizze/ct_quizze_16.zip
	M3D_Cap/ct_case/ct_case_32.zip
	M3D_Cap/ct_case/ct_case_25.zip
	M3D_Cap/ct_case/ct_case_29.zip
	M3D_Cap/ct_case/ct_case_31.zip
	M3D_Cap/ct_quizze/ct_quizze_28.zip
	M3D_Cap/ct_case/ct_case_34.zip
	M3D_Cap/ct_case/ct_case_33.zip
	M3D_Cap/ct_case/ct_case_36.zip
	M3D_Cap/ct_quizze/ct_quizze_18.zip
	M3D_Cap/ct_quizze/ct_quizze_07.zip
	M3D_Cap/ct_case/ct_case_42.zip
	M3D_Cap/ct_case/ct_case_38.zip
	M3D_Cap/ct_case/ct_case_39.zip
	M3D_Cap/ct_quizze/ct_quizze_22.zip
	M3D_Cap/ct_case/ct_case_59.zip
	M3D_Cap/ct_quizze/ct_quizze_20.zip
	M3D_Cap/ct_case/ct_case_37.zip
	M3D_Cap/ct_case/ct_case_40.zip
	M3D_Cap/ct_quizze/ct_quizze_21.zip
	M3D_Cap/ct_quizze/ct_quizze_23.zip
	M3D_Cap/ct_case/ct_case_35.zip
	M3D_Cap/ct_quizze/ct_quizze_35.zip
	M3D_Cap/ct_quizze/ct_quizze_06.zip
	M3D_Cap/ct_case/ct_case_41.zip
	M3D_Cap/ct_quizze/ct_quizze_24.zip
	M3D_Cap/ct_quizze/ct_quizze_25.zip
	M3D_Cap/ct_case/ct_case_43.zip
	M3D_Cap/ct_quizze/ct_quizze_30.zip
	M3D_Cap/ct_case/ct_case_45.zip
	M3D_Cap/ct_quizze/ct_quizze_43.zip
	M3D_Cap/ct_quizze/ct_quizze_36.zip
	M3D_Cap/ct_quizze/ct_quizze_41.zip
	test_data.zip

See: `git lfs help smudge` for more details.

**Comment by ruida** [comment]
>  python m3d_cap_data_prepare.py 
/conda/envs/m3d/lib/python3.9/site-packages/monai/utils/deprecate_utils.py:321: FutureWarning: monai.transforms.croppad.array CropForeground.__init__:allow_smaller: Current default value of argument `allow_smaller=True` has been deprecated since version 1.2. It will be changed to `allow_smaller=False` in version 1.5.
  warn_deprecated(argname, msg, warning_category)
Processing:   0%|                                                                                        | 1/24914 [02:58<1235:29:52, 178.53s/it]This image is error:  /M3D/Data/data/M3D-Cap/M3D_Cap/ct_case_unzip/000781/Axial_renal_excretory_phase/71.jpeg
Processing:   0%|                                                                                        | 1/24914 [10:10<4226:28:29, 610.74s/it]
This image is error: /M3D/Data/data/M3D-Cap/M3D_Cap/ct_case_unzip/001592/Sagittal_bone_window/71.jpeg

**Comment by baifanxxx** [comment]
Hi,

Thank you for your interest in our work. The same CT scan may have some error image slices since all images are crawled from the website. These error images are not normal PNG or JPEG images on the original website. But do not worry. There are still many available images in the same error CT scan, which renders the 3D CT scan normal.

**Comment by Zhong1015** [comment]
> Hi,
> 
> Thank you for your interest in our work. The same CT scan may have some error image slices since all images are crawled from the website. These error images are not normal PNG or JPEG images on the original website. But do not worry. There are still many available images in the same error CT scan, which renders the 3D CT scan normal.

Hello, author. Thank you for your excellent work! And I want to check whether the jpeg file error is the same as the following:

<img width="764" height="167" alt="Image" src="https://github.com/user-attachments/assets/2c7c2fac-3df5-467b-9503-2e9a516d0dec" />

And is this error do not impact the 3D Volume creation?
