### ISSUE TITLE
The weights of pretrain_mm_mlp_adapter

### ISSUE THREAD

**Issue by zhi-xuan-chen** [BAAI-DCAI/M3D#21]
Hello, can you provide the pretrained weights of pretrain_mm_mlp_adapter, which is used in finetune_lora.sh

**Comment by baifanxxx** [comment]
Hi,

You can find the ‘mm_projecter’ [here](https://huggingface.co/GoodBaiBai88/M3D-LaMed-Phi-3-4B/tree/main).
