### ISSUE TITLE
Error Loading `state_dict` for ViT

### ISSUE THREAD

**Issue by htong3031** [BAAI-DCAI/M3D#24]
### 1. Error Loading `state_dict` for ViT

While attempting to train a pretrained model using the `LaMed/script/pretrained.sh` script with a self-trained vision model specified as:

```bash
    --pretrain_vision_model ./LaMed/output/CLIP-0007/model_params.bin \
```

I encountered an error indicating that the vision model lacks certain keys in the state dictionary that are required by the ViT (Vision Transformer) model:

```bash
RuntimeError: Error(s) in loading state_dict for ViT:
        Missing key(s) in state_dict: "cls_token", "patch_embedding.position_embeddings", "patch_embedding.patch_embeddings.1.weight", "patch_embedding.patch_embeddings.1.bias", 
        -- snip --
```

This issue does not occur when using the recommended Medical 3D ViT weights (`pretrained_ViT.bin`) from the [[M3D-CLIP](https://huggingface.co/GoodBaiBai88/M3D-CLIP/tree/main)](https://huggingface.co/GoodBaiBai88/M3D-CLIP/tree/main) model.

### 2. Consistency Between M3DCLIP Models

Initially, I assumed the error was caused by architectural incompatibilities between the vision model I trained from scratch and the provided M3D-CLIP model. However, I verified the structure of both models using the following script and confirmed that their state dictionaries are consistent, with no missing keys:

```python
from LaMed.src.model.CLIP import M3DCLIP

model1 = M3DCLIP.from_pretrained("./LaMed/pretrained_model/M3D-CLIP/")
model2 = M3DCLIP.from_pretrained("./LaMed/output/CLIP-0007/")

state_dict1 = model1.state_dict()
state_dict2 = model2.state_dict()

missing_keys = set(state_dict1.keys()) - set(state_dict2.keys())
print(f"Missing keys in model2: {missing_keys}")

missing_keys = set(state_dict2.keys()) - set(state_dict1.keys())
print(f"Missing keys in model1: {missing_keys}")

# Missing keys in model2: set()
# Missing keys in model1: set()
```

### 3. Error in Strictly Load in `bin` files

The error appears to stem from loading the `bin` files. The following minimal code reproduces the issue, where the vision tower is successfully initialized using the recommended `./GoodBaiBai88/M3D-CLIP/pretrained_ViT.bin`:

```python
from LaMed.src.model.multimodal_encoder.builder import build_vision_tower
import torch

class LamedConfig:
    # Configuration details as in the original post
    ...

# Create the config instance
lamed_config = LamedConfig()
vision_tower = build_vision_tower(lamed_config)
vision_model_weights = torch.load("./GoodBaiBai88/M3D-CLIP/pretrained_ViT.bin", 
                                  map_location='cpu')
vision_tower.load_state_dict(vision_model_weights, strict=True)

# No error
```

However, when attempting to load the state dictionary with weights trained from scratch and with the `strict` parameter enabled, the following error occurs:

```python
# Create the config instance
lamed_config = LamedConfig()
vision_tower = build_vision_tower(lamed_config)
vision_model_weights = torch.load("./LaMed/pretrained_model/M3D-CLIP/pretrained_ViT.bin", 
                                   map_location='cpu')
vision_tower.load_state_dict(vision_model_weights, strict=True)

# Error occurs here
```

```bash
RuntimeError: Error(s) in loading state_dict for ViT3DTower:
        Missing key(s) in state_dict: "vision_tower.cls_token", "vision_tower.patch_embedding.position_embeddings", 
        -- snip --
        Unexpected key(s) in state_dict: "logit_scale", "vision_encoder.cls_token", "vision_encoder.patch_embedding.position_embeddings", 
        -- snip --
```

### 4. Clarification Requested

Could you please provide clarification on why this error occurs when loading the state dict with `strict=True`, and how to obtain a properly formatted `bin` file similar to `./GoodBaiBai88/M3D-CLIP/pretrained_ViT.bin` to avoid this issue.

Additionally, I would also like to know why the `M3DCLIP` model loads successfully, but the `vision_tower` component fails during loading.

Thank you for your assistance.

**Comment by baifanxxx** [comment]
Hi,

I'm sorry for my late reply as I've been busy lately. But I'll deal with your questions as soon as I have time, which makes me feel meaningful.

To get to the point, you can check that the definitions of the [M3D-CLIP](https://github.com/BAAI-DCAI/M3D/blob/0ff4a7aed832b191dbad16eb3d9a46238da65a23/LaMed/src/model/CLIP.py#L57) and [M3D-Lamed](https://github.com/BAAI-DCAI/M3D/blob/0ff4a7aed832b191dbad16eb3d9a46238da65a23/LaMed/src/model/multimodal_encoder/vit.py#L139) in the vision models with different names. You need to convert the names when loading the pre-trained parameters.

**Comment by Khawaja-Murad** [comment]
@htong3031 have you been able to run it?

**Comment by htong3031** [comment]
> [@htong3031](https://github.com/htong3031) have you been able to run it?

Yes. Refer to the author's reply the pipeline works.

**Comment by Khawaja-Murad** [comment]
> > [@htong3031](https://github.com/htong3031) have you been able to run it?
> 
> Yes. Refer to the author's reply the pipeline works.

@htong3031 if its cool can you please share your repo or the exact changes you did to achieve this, its just I am on a deadline and help from a fellow community member would be really appreciated. Thanks

**Comment by htong3031** [comment]
> > > [@htong3031](https://github.com/htong3031) have you been able to run it?
> > 
> > 
> > Yes. Refer to the author's reply the pipeline works.
> 
> [@htong3031](https://github.com/htong3031) if its cool can you please share your repo or the exact changes you did to achieve this, its just I am on a deadline and help from a fellow community member would be really appreciated. Thanks

Yes. I have run it successfully. As author suggested, you need to convert the block names when loading the pre-trained parameters. I simply replaced the key names in the model. 

```python
# Filter out the weights for the ViT model
vit_weights = {k.replace('vision_encoder.', ''): v for k, v in vision_model_weights.items() if k in vit_keys}
