### ISSUE TITLE
Python environment to run

### ISSUE THREAD

**Issue by morganrcu** [BAAI-DCAI/M3D#26]
Hi folks,

I'm trying to run your code locally but I'm suffering to do it on windows. 
What python/cuda version shall I use?

Kind regards,

Rodrigo

**Comment by AndyQin92** [comment]
I can run it with python3.11 and torch2.2.1 cuda11.8 on linux.

**Comment by baifanxxx** [comment]
Hi,

You can refer to [this](https://github.com/BAAI-DCAI/M3D/blob/main/requirements.txt). Higher versions should also be possible. The project's dependence on versions is not too serious. You can try using different versions.
