### ISSUE TITLE
Can you tell me how the VQA datasets are differentiated?

### ISSUE THREAD

**Issue by Faithyf** [BAAI-DCAI/M3D#27]
Hello, I was reading your paper and saw that the experiments you did on the VQA dataset were categorized into closed-ended VQA and open-ended VQA, but I downloaded the link to the dataset you gave and there is no differentiation in it, can you provide the documentation to differentiate between the two categories please?

**Comment by baifanxxx** [comment]
Hi,

You can find the differences [here](https://github.com/BAAI-DCAI/M3D/blob/0ff4a7aed832b191dbad16eb3d9a46238da65a23/Bench/dataset/multi_dataset.py#L301). We construct a VQA multiple-choice question dataset, but two different settings, open set and closed set, can be used for evaluation.
