### ISSUE TITLE
Description of the model `M3D-LaMed-Phi-3-4B` in the paper? Demo script fails with this model.

### ISSUE THREAD

**Issue by YongchengYAO** [BAAI-DCAI/M3D#29]
Could you indicate where the description of the model `M3D-LaMed-Phi-3-4B` is in the paper?

The demo script fails on running this model, with the same error as this issue https://github.com/BAAI-DCAI/M3D/issues/15#issue-2476319857

**Comment by DanyalMaq** [comment]
try installing `transformers==4.4.1`

**Comment by YongchengYAO** [comment]
Solved.

Observation: lower version of transformers (< 4.40) would result in error: [~can not find config for Phi3]

Model inference for  `M3D-LaMed-Phi-3-4B` is working with these packages:

'''
deepspeed==0.14.4
einops==0.8.0
evaluate==0.4.1
matplotlib==3.8.4
monai==1.3.0
nibabel==5.2.1
numpy==1.26.4
opencv_python==4.9.0.80
pandas==2.2.2
peft==0.8.2
Pillow==10.3.0
pycocotools==2.0.7
Requests==2.31.0
rouge==1.0.1
safetensors==0.4.3
scipy==1.13.0
simple_slice_viewer==0.97
SimpleITK==2.3.1

tqdm==4.66.2

transformers==4.45 

bitsandbytes==0.41.0

tweepy==4.14.0
protobuf==5.28.3
sentencepiece== 0.2.0

torch==2.5.1
torchvision==0.20.1
'''
