### ISSUE TITLE
How many training samples are used?

### ISSUE THREAD

**Issue by wjhou** [BAAI-DCAI/M3D#3]
Hi, 

Thanks for your contributions and for releasing the dataset.

I am conducting a follow-up research on the M3D paper and after reading the content, I could not find details about the training samples used in training, given the huge amount of images (~100K samples x ~300/sample = 3M images). 

Since the test samples used are quite small, did you use all the samples or just part of them for training? If only a portion of the training samples were used, could you also release the corresponding IDs so that I can keep these samples?

Best,
Ethan

**Comment by baifanxxx** [comment]
Hi, 

Detailed split information is in the released dataset. You can find the details about training samples and test ID. 

Best regards,
BAI Fan
