### ISSUE TITLE
Questions related to M3D-CLIP weights

### ISSUE THREAD

**Issue by bmcbmcbm** [BAAI-DCAI/M3D#4]
Hello,

Thank you for sharing your project code and associated weights. I would like to inquire about the weights published on Hugging Face under M3D-CLIP/pretrained_ViT.bin. Are these weights extracted from the visual encoder of a CLIP model trained with M3D-Cap? If I want to use the visual encoder of M3D-CLIP, can I directly use the pretrained_ViT.bin weights for this purpose?

Thank you for your time and assistance.

**Comment by baifanxxx** [comment]
Hi, 

Of course, you can use the pretrained_ViT.bin directly because this weight is extracted from the M3D-CLIP.

**Comment by bmcbmcbm** [comment]
thank you and may I ask if the dataset includes only CT modalities for medical images?

**Comment by baifanxxx** [comment]
Hi, 

We focus on CT modality now. But the model is universal. You can add other 3D modalities to the dataset directly.

**Comment by bmcbmcbm** [comment]
Thank you very much
