### ISSUE TITLE
Phi3ForCausalLM not support Image input?

### ISSUE THREAD

**Issue by zhouhoo** [BAAI-DCAI/M3D#44]
Hi, when I train step by step as the readme show, I got a local  train model output as follow:
`{
  "_name_or_path": "microsoft/Phi-3-mini-4k-instruct",
  "architectures": [
    "LamedPhi3ForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "microsoft/Phi-3-mini-4k-instruct--configuration_phi3.Phi3Config",
    "AutoModelForCausalLM": "microsoft/Phi-3-mini-4k-instruct--modeling_phi3.Phi3ForCausalLM"
  },
  "bos_token_id": 1,
  "embd_pdrop": 0.0,
  "eos_token_id": 32000,
  "hidden_act": "silu",
  "hidden_size": 3072,
  "image_channel": 1,
  "image_size": [
    32,
    256,
    256
  ],
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 4096,
  "mm_hidden_size": 768,
  "mm_projector_type": "spp",
  "model_type": "lamed_phi3",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "original_max_position_embeddings": 4096,
  "pad_token_id": 32000,
  "patch_size": [
    4,
    16,
    16
  ],
  "proj_layer_num": 2,
  "proj_layer_type": "mlp",
  "proj_pooling_size": 2,
  "proj_pooling_type": "spatial",
  "resid_pdrop": 0.0,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "seg_token_id": 32014,
  "sliding_window": 2047,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.44.1",
  "use_cache": true,
  "vision_select_feature": "patch",
  "vision_select_layer": -1,
  "vision_tower": "vit3d",
  "vocab_size": 32015
}
`

but when I try to eval it and run the` eval_vqa.py ` , I got the error as follow:
`Traceback (most recent call last):
  File "/root/M3D/Bench/eval/eval_vqa.py", line 161, in <module>
    main()
  File "/root/M3D/Bench/eval/eval_vqa.py", line 113, in main
    generation = model.generate(image, input_id, max_new_tokens=args.max_new_tokens,
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1324, in generate
    generation_config, model_kwargs = self._prepare_generation_config(generation_config, **kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1220, in _prepare_generation_config
    model_kwargs = generation_config.update(**kwargs)
AttributeError: 'Tensor' object has no attribute 'update'`

I search the internet and [some says](https://docs.vllm.ai/en/latest/models/supported_models.html) "Phi3ForCausalLM 模型，这是一个纯语言模型而不是多模态模型。这就解释了为什么 generate() 方法不接受图像输入。" 
so can you give me some advice ?

**Comment by zhouhoo** [comment]
@BAAI-DCAI

**Comment by Marshall-mk** [comment]
Were you able to resolve this issue? I am facing the same.
